/*
 * Users and Auth Apis
 * This service container user related apis and auth apis
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.35
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UsersAndAuthApis);
  }
}(this, function(expect, UsersAndAuthApis) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UsersAndAuthApis.DefaultApi();
  });

  describe('(package)', function() {
    describe('DefaultApi', function() {
      describe('registerPost', function() {
        it('should call registerPost successfully', function(done) {
          // TODO: uncomment, update parameter values for registerPost call and complete the assertions
          /*

          instance.registerPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(UsersAndAuthApis.User);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
